apiVersion: v2
name: em-anno
home: https://github.com/hmcts/em-annotation-api
version: 1.0.17
description: Helm chart for the HMCTS EM Annotation API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.0.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
