java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    em-anno:
      secrets:
        - name: microservicekey-em-annotation-app
          alias: S2S_KEY
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/javadatabase?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
    ENABLE_METADATA_ENDPOINT: true
    RUN_DB_MIGRATION_ON_STARTUP: true
  postgresql:
    enabled: true
    auth:
      username: emannotationapp
      password: emannotationapp
