java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    em-anno:
      secrets:
        - name: microservicekey-em-annotation-app
          alias: S2S_KEY
  environment:
    SPRING_DATASOURCE_HOST: "{{ .Release.Name }}-postgresql"
    SPRING_DATASOURCE_NAME: "{{ .Values.postgresql.auth.database}}"
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.auth.username}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    SPRING_DATASOURCE_OPTIONS: "?ssl=disable"
    OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
    ENABLE_METADATA_ENDPOINT: true
    RUN_DB_MIGRATION_ON_STARTUP: true
  postgresql:
    enabled: true