
ALTER TABLE annotation ADD CONSTRAINT FK_ANNOTATION_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE annotation ADD CONSTRAINT FK_ANNOTATION_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE annotation_set ADD CONSTRAINT FK_ANNOTATION_SET_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE annotation_set ADD CONSTRAINT FK_ANNOTATION_SET_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE rectangle ADD CONSTRAINT FK_RECTANGLE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE rectangle ADD CONSTRAINT FK_RECTANGLE_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE annotation_tags ADD CONSTRAINT fk_anntag_on_tag FOREIGN KEY (name) REFERENCES tag (name);

ALTER TABLE annotation_tags DROP CONSTRAINT FK9qipuwcr39qbh75i74xe682kg;

DROP TABLE jhi_authority CASCADE;

ALTER TABLE annotation_tags DROP COLUMN created_by;

ALTER TABLE annotation ALTER COLUMN color TYPE VARCHAR(255) USING (color::VARCHAR(255));

ALTER TABLE tag ALTER COLUMN color TYPE VARCHAR(20) USING (color::VARCHAR(20));

ALTER TABLE rectangle DROP COLUMN height;

ALTER TABLE rectangle DROP COLUMN width;

ALTER TABLE rectangle DROP COLUMN x;

ALTER TABLE rectangle DROP COLUMN y;

ALTER TABLE rectangle ADD height DOUBLE PRECISION;

ALTER TABLE jhi_persistent_audit_evt_data ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE jhi_persistent_audit_event ALTER COLUMN principal TYPE VARCHAR(255) USING (principal::VARCHAR(255));

ALTER TABLE rectangle ADD width DOUBLE PRECISION;

ALTER TABLE rectangle ADD x DOUBLE PRECISION;

ALTER TABLE rectangle ADD y DOUBLE PRECISION;

ALTER TABLE annotation_tags ADD CONSTRAINT pk_annotation_tags PRIMARY KEY (annotation_id, name);

ALTER TABLE tag ADD CONSTRAINT pk_tag PRIMARY KEY (name);
ALTER TABLE annotation ADD CONSTRAINT FK_ANNOTATION_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE annotation ADD CONSTRAINT FK_ANNOTATION_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE annotation_set ADD CONSTRAINT FK_ANNOTATION_SET_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE annotation_set ADD CONSTRAINT FK_ANNOTATION_SET_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE rectangle ADD CONSTRAINT FK_RECTANGLE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES idam_details (id);

ALTER TABLE rectangle ADD CONSTRAINT FK_RECTANGLE_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES idam_details (id);

ALTER TABLE annotation_tags ADD CONSTRAINT fk_anntag_on_tag FOREIGN KEY (name) REFERENCES tag (name);

ALTER TABLE annotation_tags DROP CONSTRAINT FK9qipuwcr39qbh75i74xe682kg;

DROP TABLE jhi_authority CASCADE;

ALTER TABLE annotation_tags DROP COLUMN created_by;

ALTER TABLE annotation ALTER COLUMN color TYPE VARCHAR(255) USING (color::VARCHAR(255));

ALTER TABLE tag ALTER COLUMN color TYPE VARCHAR(20) USING (color::VARCHAR(20));

ALTER TABLE rectangle DROP COLUMN height;

ALTER TABLE rectangle DROP COLUMN width;

ALTER TABLE rectangle DROP COLUMN x;

ALTER TABLE rectangle DROP COLUMN y;

ALTER TABLE rectangle ADD height DOUBLE PRECISION;

ALTER TABLE jhi_persistent_audit_evt_data ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE jhi_persistent_audit_event ALTER COLUMN principal TYPE VARCHAR(255) USING (principal::VARCHAR(255));

ALTER TABLE rectangle ADD width DOUBLE PRECISION;

ALTER TABLE rectangle ADD x DOUBLE PRECISION;

ALTER TABLE rectangle ADD y DOUBLE PRECISION;

ALTER TABLE annotation_tags ADD CONSTRAINT pk_annotation_tags PRIMARY KEY (annotation_id, name);

ALTER TABLE tag ADD CONSTRAINT pk_tag PRIMARY KEY (name);